name: Build

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Node.js 14.17.0
      uses: actions/setup-node@master
      with:
        node-version: 14.17.0

    - name: Install dependencies
      run: yarn

    - name: Run lint check
      run: yarn lint

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Node.js 14.17.0
      uses: actions/setup-node@master
      with:
        node-version: 14.17.0

    - name: Install dependencies
      run: yarn

    - name: Run test suite
      run: yarn test
